### ISSUE TITLE
Override right-click harvest while plant is not grown

### ISSUE THREAD

**Issue by NielsPilgaard** [codetaylor/ct-watercan#16]
Hello!

I use Simple Farming's right-click harvest functionality in my modpack, and it makes it impossible to use your Watering Cans while looking at crops, grown or not, even while holding sneak.
It would be nice if I could aim the watering can at non-grown crops, to get even water spread.

**Comment by codetaylor** [comment]
I've reviewed this and because of the way Simple Farming's right-click harvest feature is written, I'm not sure there is anything I can do about it from my end.

https://github.com/enemeez/simplefarming/blob/master/src/main/java/enemeez/simplefarming/events/harvest/CropHarvest.java#L54

Simple Farming's logic is basically if the player is not holding bone meal, has right-clicked a crop, and is holding an item, cancel the right-click event which prevents a held item from being used. This occurs regardless of whether or not the crop can actually be harvested.

**Comment by NielsPilgaard** [comment]
I see, thank you very much for having a go at it, and the explaination. I'll take it to the Simple Farming developer :)
