### ISSUE TITLE
Crashes before it even starts the loading screen

### ISSUE THREAD

**Issue by varappdev** [codetaylor/ct-watercan#9]
It crashed before the loading screen even show up. And I was using the beta version.
 https://pastebin.com/2fW6hCa7

**Comment by codetaylor** [comment]
It looks like you're missing the Athenaeum lib dependency.

You can download it here:
https://minecraft.curseforge.com/projects/athenaeum/files

I fixed the missing dependency declaration here: 54b37100c56b21a5842f6167ae6d07bdd0bb6d2b

The mod should now fail to load when it's missing its Athenaeum dependency, but it'll tell you why.

Fixed in version 1.12.2-1.1.2
